'use strict';

let CONSTANTS = {};

CONSTANTS.SERVER = {
  ADMINPASSWORD: process.env.ADMIN_PASSWORD,
  ONE: 1,
  INDEX_NOT_FOUND: -1,
  RESPONSE_TIMEOUT: 300000,
  MINUTE_IN_1_HOUR: 60
};

CONSTANTS.SUBMITTION_STATUSES = {
  PENDING: 1,
  PASS: 2,
  FAIL: 3
};

CONSTANTS.USER_ROLES = {
  NORMAL: 1,
  ADMIN: 2
};

CONSTANTS.AVAILABLE_AUTHS = {
  USER: 'user',
};

CONSTANTS.PASSWORD_PATTER_REGEX = /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.NORMAL_PROJECTION = { __v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0 };

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.SECURITY = {
  JWT_SIGN_KEY: 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads',
  BCRYPT_SALT: 8,
  STATIC_TOKEN_FOR_AUTHORIZATION: '58dde3df315587b279edc3f5eeb98145'
};

CONSTANTS.ERROR_TYPES = {
  DATA_NOT_FOUND: 'DATA_NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  MONGO_EXCEPTION: 'MONGO_EXCEPTION',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  TIMEOUT: 'TIMEOUT'
};


CONSTANTS.AVAILABLE_EXT_FOR_UPLOAD = ['zip', 'pdf'];

CONSTANTS.EMAIL_SUBJECTS = {
  WELCOME_VERIFICATION_EMAIL: 'User Verification Email:  demo',
  FORGOT_PASSWORD_EMAIL: 'Forgot Password: demo'
};

CONSTANTS.EMAIL_TYPES = {
  WELCOME_VERIFICATION_EMAIL: 1,
  FORGOT_PASSWORD_EMAIL: 2,
  FORGOT_PASSWORD_EMAIL_UPDATED: 3
};

module.exports = CONSTANTS;
